#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDOK                                    1
#define VS_VERSION_INFO                         1
#define IDCANCEL                                2
#define IDD_MEM                                 101
#define IDD_ULA                                 105
#define IDD_LEDS                                106
#define IDD_SOUND                               107
#define IDD_VTX                                 108
#define IDD_TAPE                                109
#define IDD_BETA128                             110
#define IDD_POKE                                113
#define IDI_MAIN                                115
#define IDD_INPUT                               116
#define IDD_ARC                                 117
#define IDD_COND                                127
#define IDD_GS                                  128
#define IDD_OSW                                 129
#define IDD_VIDEO                               130
#define IDD_CHIP                                131
#define IDD_EFF7                                132
#define IDD_FONTS                               133
#define IDD_HDD                                 134
#define IDD_LABELS                              135
#define IDD_FILTER_DIALOG                       137
#define IDD_CHEAT                               138
#define IDC_C0                                  139
#define IDC_C1                                  140
#define IDC_C2                                  141
#define IDC_C3                                  142
#define IDC_C4                                  143
#define IDC_C5                                  144
#define IDC_C6                                  145
#define IDC_C7                                  146
#define IDC_C8                                  147
#define IDR_DEBUGMENU                           151
#define IDR_MAINMENU                            152
#define IDD_TSUTOGGLE                           153
#define IDC_VDAC                                1000
#define IDE_FRAME                               1013
#define IDE_LINE                                1014
#define IDC_LED_ON                              1019
#define IDC_LED_AY                              1020
#define IDC_LED_AY_X                            1021
#define IDE_DISK_A                              1021
#define IDE_POKE                                1021
#define IDE_SKIP1                               1021
#define IDC_LED_ROM_X                           1022
#define IDE_SKIP2                               1022
#define IDC_LED_LOAD                            1023
#define IDC_LED_INPUT_X                         1024
#define IDC_LED_INPUT                           1025
#define IDC_NOSOUND                             1026
#define IDC_SND_BEEPER                          1027
#define IDC_SND_MICOUT                          1028
#define IDC_SND_MICIN                           1029
#define IDC_SND_AY                              1030
#define IDC_MEM                                 1031
#define IDC_SOUNDFILTER                         1031
#define IDC_SND_COVOXFB                         1034
#define IDC_SND_COVOXDD                         1035
#define IDC_VIDEOFILTER                         1036
#define IDC_BORDERSIZE                          1037
#define IDC_TAPE                                1037
#define IDC_LED_AY_Y                            1039
#define IDC_LED_ROM_Y                           1040
#define IDC_LED_INPUT_Y                         1041
#define IDC_LED_PERF_X                          1042
#define IDC_LED_PERF_Y                          1043
#define IDC_LED_PERF                            1044
#define IDB_INS_A                               1045
#define IDB_REM_A                               1046
#define IDC_BETA128                             1047
#define IDC_DISK_NODELAY                        1048
#define IDB_INS_B                               1049
#define IDB_REM_B                               1050
#define IDE_DISK_B                              1051
#define IDE_DISK_C                              1052
#define IDB_INS_C                               1053
#define IDB_REM_C                               1054
#define IDE_DISK_D                              1055
#define IDB_INS_D                               1056
#define IDB_REM_D                               1057
#define IDC_LED_AYKBD                           1063
#define IDC_MOUSESCALE                          1065
#define IDC_KEYMATRIX                           1066
#define IDC_MOUSESWAP                           1067
#define IDC_KJOY                                1069
#define IDC_ARCLIST                             1070
#define IDC_FLIP                                1071
#define IDE_INT                                 1072
#define IDC_WPB                                 1073
#define IDE_INT_LEN                             1073
#define IDC_WPC                                 1074
#define IDC_WPD                                 1075
#define IDC_SND_BASS                            1076
#define IDC_SND_GS                              1077
#define IDB_SAVEMOD                             1078
#define IDC_CBP                                 1079
#define IDC_BPX                                 1080
#define IDE_CBP                                 1081
#define IDB_CBP_ADD                             1082
#define IDB_CBP_DEL                             1083
#define IDE_BPX                                 1084
#define IDB_BPX_ADD                             1085
#define IDC_GSLIST                              1085
#define IDB_BPX_DEL                             1086
#define IDB_GS_PLAY                             1087
#define IDE_MEM                                 1087
#define IDB_GS_RESET                            1088
#define IDB_MEM_ADD                             1088
#define IDB_MEM_DEL                             1089
#define IDE_GS                                  1090
#define IDB_GS_CLEAR                            1091
#define IDC_NOPAPER                             1092
#define IDC_VTXCHIP                             1094
#define IDC_FIREKEY                             1097
#define IDC_PALETTE                             1097
#define IDC_ROMPAGE                             1097
#define IDC_LED_TIME_X                          1098
#define IDC_RENDER                              1098
#define IDE_ROMNAME                             1098
#define IDC_LED_TIME_Y                          1099
#define IDC_SCRSHOT                             1099
#define IDE_FIRERATE                            1099
#define IDE_HOLD_DELAY                          1100
#define IDE_VTXNAME                             1100
#define IDC_FILEPAGE                            1101
#define IDE_RELEASE_DELAY                       1101
#define IDE_VTXAUTH                             1101
#define IDB_ROMSEL_S                            1102
#define IDE_NEWLINE_DELAY                       1102
#define IDE_VTXSOFT                             1102
#define IDC_ROMSET                              1103
#define IDE_VTXTRACK                            1103
#define IDC_EVENM1                              1104
#define IDC_FILEBANK                            1104
#define IDE_VTXCOMM                             1104
#define IDC_4TBORDER                            1105
#define IDE_VTXYEAR                             1105
#define IDB_ROMSEL_P                            1106
#define IDC_LED_TIME                            1107
#define IDC_GSRESET                             1108
#define IDC_AUTOFIRE                            1109
#define IDC_SPIN1                               1110
#define IDC_JOYMOUSE                            1111
#define IDC_PERF_T                              1111
#define IDC_W1_ON                               1111
#define IDC_WPA                                 1111
#define IDC_SPIN2                               1112
#define IDE_W1                                  1112
#define IDC_SPIN3                               1113
#define IDC_W2_ON                               1113
#define IDC_SPIN4                               1114
#define IDE_W2                                  1114
#define IDC_W3_ON                               1115
#define IDE_W3                                  1116
#define IDC_W4_ON                               1117
#define IDE_W4                                  1118
#define IDC_TR_RAM                              1119
#define IDC_TR_ROM                              1120
#define IDC_LED_DEBUG                           1121
#define IDC_LED_DEBUG_X                         1122
#define IDE_MINX                                1122
#define IDC_LED_DEBUG_Y                         1123
#define IDE_SCBRIGHT                            1123
#define IDC_KLAYOUT                             1126
#define IDC_MODEM                               1127
#define IDC_FLASH                               1132
#define IDC_ULAPLUS                             1133
#define IDC_ALT_NOFLIC                          1136
#define IDC_DISK_TRAPS                          1136
#define IDB_SAVE_A                              1137
#define IDB_SAVE_B                              1138
#define IDB_SAVE_C                              1139
#define IDB_SAVE_D                              1140
#define IDC_NOFLIC                              1150
#define IDC_TAPE_AUTOSTART                      1151
#define IDC_BASS_TITLE                          1152
#define IDC_GS_TITLE                            1153
#define IDC_CHIP_BUS                            1154
#define IDC_CHIP_VOL                            1155
#define IDC_ULAPRESET                           1155
#define IDC_CHIP_STEREO                         1156
#define IDC_CHIP_CLK                            1157
#define IDC_CHIP_SCHEME                         1158
#define IDC_REND_TITLE                          1160
#define IDC_BIT0                                1163
#define IDC_BIT1                                1164
#define IDC_BIT2                                1165
#define IDC_BIT3                                1166
#define IDC_REND_TITLE2                         1166
#define IDC_BIT4                                1167
#define IDC_B_TITLE2                            1167
#define IDC_BIT5                                1168
#define IDC_BIT6                                1169
#define IDC_BIT7                                1170
#define IDC_LOCK0                               1171
#define IDC_LOCK1                               1172
#define IDE_ADDRESS                             1172
#define IDC_LOCK2                               1173
#define IDC_LOCK3                               1174
#define IDC_SPIN                                1174
#define IDC_100                                 1175
#define IDC_LOCK4                               1175
#define IDC_ADDRESS                             1176
#define IDC_LOCK5                               1176
#define IDC_LINEAR                              1177
#define IDC_LOCK6                               1177
#define IDC_LOCK7                               1178
#define IDC_PLANES                              1178
#define IDC_LEFT                                1179
#define IDC_RIGHT                               1180
#define IDC_ALTLOCK                             1181
#define IDC_R3039                               1183
#define IDC_R415A                               1184
#define IDC_R617A                               1185
#define IDC_R809F                               1186
#define IDC_RA0AF                               1187
#define IDC_RF0F1                               1188
#define IDC_R212F                               1189
#define IDC_ROTH2                               1190
#define IDC_FRAME                               1191
#define IDC_FIND                                1192
#define IDC_FILE                                1193
#define IDC_FONTSIZE                            1195
#define IDC_MODA                                1200
#define IDC_SND_SD                              1200
#define IDC_IDESCHEME                           1201
#define IDC_MODB                                1201
#define IDC_MODC                                1202
#define IDE_HDD0                                1202
#define IDB_HDD0                                1203
#define IDC_MODD                                1203
#define IDE_HDD0_CHS                            1204
#define IDE_HDD0_LBA                            1205
#define IDE_HDD1                                1206
#define IDB_HDD1                                1207
#define IDE_HDD1_CHS                            1208
#define IDE_HDD1_LBA                            1209
#define IDS_HDD1_CHS                            1210
#define IDS_HDD1_LBA                            1211
#define IDS_HDD0_CHS                            1212
#define IDS_HDD0_LBA                            1213
#define IDC_HDD0_RO                             1214
#define IDC_HDD1_RO                             1215
#define IDC_RAM128                              1215
#define IDC_RAM256                              1216
#define IDC_RAM512                              1217
#define IDC_RAM1024                             1218
#define IDC_SINGLE_ROM                          1219
#define IDC_CUSTOM_ROM                          1220
#define IDC_CACHE0                              1221
#define IDC_CACHE16                             1222
#define IDC_CACHE32                             1223
#define IDC_CMOS_NONE                           1224
#define IDC_CMOS_DALLAS                         1225
#define IDC_CMOS_RUS                            1226
#define IDC_TOTAL_ROM                           1227
#define IDC_FLOAT_BUS                           1228
#define IDC_RAM4096                             1228
#define IDC_FLOAT_DOS                           1229
#define IDE_BIGROM                              1229
#define IDC_MEM_R                               1230
#define IDC_PORT_FF                             1230
#define IDC_MEM_W                               1231
#define IDC_SMUC                                1232
#define IDC_MOUSE_NONE                          1233
#define IDC_LABELS                              1234
#define IDC_MOUSE_KEMPSTON                      1234
#define IDC_LABEL_TEXT                          1235
#define IDC_MOUSE_AY                            1235
#define IDC_CHIP_DIGITAL                        1236
#define IDC_LISTBOX                             1243
#define IDC_RESULTS                             1243
#define IDC_LED_MEMBAND                         1246
#define IDC_LED_MEMBAND_X                       1247
#define IDC_LED_MEMBAND_Y                       1248
#define IDC_LED_BPP                             1249
#define IDD_FILEPREVIEW                         1251
#define IDC_PREVIEW_BOX                         1252
#define IDC_PREVIEW_BASIC                       1253
#define IDC_PREVIEW_ERASED                      1254
#define IDC_NEW                                 1255
#define IDC_EXACT                               1256
#define IDC_INC                                 1257
#define IDC_DEC                                 1258
#define IDC_BYTE                                1259
#define IDC_WORD                                1260
#define IDB_SEARCH                              1261
#define IDE_VALUE                               1262
#define IDC_HEX                                 1263
#define IDC_STATUS                              1264
#define IDC_PC_LAYOUT                           10050
#define IDC_WHEEL_NONE                          10252
#define IDC_WHEEL_KEYBOARD                      10254
#define IDC_WHEEL_KEMPSTON                      10256
#define IDC_RAM2048                             40000
#define IDC_SND_SAA                             40000
#define IDC_TAPE_TRAPS                          40000
#define IDE_INTSTART                            40000
#define IDM_DEBUG_RUN                           40000
#define IDM_EXIT                                40000
#define IDC_SND_COVOXPROFI                      40001
#define IDM_DEBUG_STEP                          40001
#define IDM_LOAD                                40001
#define IDC_SND_MOONSOUND                       40002
#define IDM_DEBUG_STEPOVER                      40002
#define IDM_SAVE                                40002
#define IDM_DEBUG_TILLRETURN                    40003
#define IDM_SAVE_DISKB                          40003
#define IDM_DEBUG_RUNTOCURSOR                   40004
#define IDM_SAVE_DISKC                          40004
#define IDM_MON_SCALE2X                         40005
#define IDM_SAVE_DISKD                          40005
#define IDM_MON_LOADBLOCK                       40006
#define IDM_QUICKLOAD_1                         40006
#define IDM_MON_SAVEBLOCK                       40007
#define IDM_QUICKLOAD_2                         40007
#define IDM_MON_FILLBLOCK                       40008
#define IDM_QUICKLOAD_3                         40008
#define IDM_MON_RIPPER                          40009
#define IDM_QUICKSAVE_1                         40009
#define IDM_BREAKPOINT_MANAGER                  40010
#define IDM_QUICKSAVE_2                         40010
#define IDM_BREAKPOINT_TOGGLE                   40011
#define IDM_QUICKSAVE_3                         40011
#define IDM_RESET                               40012
#define IDM_RESET_SERVICE                       40013
#define IDM_RESET_CACHE                         40014
#define IDM_RESET_128                           40015
#define IDM_RESET_48                            40016
#define IDM_RESET_DOS                           40017
#define IDM_NMI_CACHE                           40018
#define IDM_RESET_GS                            40019
#define IDM_NMI                                 40020
#define IDM_NMI_DOS                             40021
#define IDM_AUDIOREC                            40022
#define IDM_MAKESCREENSHOT                      40023
#define IDM_SETTINGS                            40024
#define IDM_VIDEOFILTER                         40025
#define IDM_FULLSCREEN                          40026
#define IDM_MAXIMUMSPEED                        40027
#define IDM_TAPE_CONTROL                        40028
#define IDM_USETAPETRAPS                        40029
#define IDM_AUTOSTARTTAPE                       40030
#define IDM_PAUSE                               40031
#define IDM_HELP_SHORTKEYS                      40032
#define IDM_HELP_ABOUT                          40033
#define IDM_POKE                                40034
#define IDM_DEBUGGER                            40040
#define IDC_TSUTOGGLE_GFX                       40044
#define IDC_TSUTOGGLE_TILE0                     40045
#define IDC_TSUTOGGLE_TILE1                     40046
#define IDC_TSUTOGGLE_SPRITE                    40047
