#ifndef SETUP_H
#define SETUP_H

#include "mytypes.h"

u8 setup_try_boot_config();
void setup_init();
void setup_task();

#ifdef SETUP_CONF
#include "tsspiffs.h"
#include "ff.h"

typedef struct
{
  u8 cursor;
  u8 scroll;
  u8 count;
} SetupPanel;

u8 setup_any_dialog_visible();
void setup_put_cell(u8 x, u8 ch, u8 attr);
void setup_clear_line(u8 ch, u8 attr);
void setup_put_text(u8 x, const char *text, u8 attr);
void setup_put_text_p(u8 x, const char *text, u8 attr);
void setup_put_panel_frame(u8 x, u8 w, u8 row);
void setup_put_panel_title_free(u8 panel, u8 x, u8 free_x, u32 free_size);
void setup_put_titles();
void setup_write_row(u8 row);
void setup_write_row_range(u8 row, u8 x, u8 w);
void setup_write_attr_row_range(u8 row, u8 x, u8 w);
void setup_clear_dialog_row(u8 x, u8 w);
u8 setup_pstr_len(const char *text);
void setup_put_dialog_title(u8 x, u8 w, const char *text);
void setup_draw_dialog_frame_row(u8 x, u8 y, u8 w, u8 h, u8 row);
u8 setup_calc_progress(u32 done, u32 total, u8 bar_w);
void setup_draw_progress_bar(u8 x, u8 w, u8 progress, u8 empty_attr);
void setup_redraw_progress_row(u8 row, u8 box_x, u8 box_w, u8 bar_x, u8 bar_w, u8 progress, u8 empty_attr);
void setup_dialog_backup_save(u8 x, u8 y, u8 w, u8 h);
void setup_dialog_backup_save_drawn_row(u8 row);
void setup_dialog_backup_restore();
void setup_dialog_backup_restore_or_redraw(u8 x, u8 y, u8 w, u8 h);
void setup_dialog_backup_save_if_needed(u8 x, u8 y, u8 w, u8 h);
u8 setup_dialog_get_rect(u8 *x, u8 *y, u8 *w, u8 *h);
void setup_workspace_init();
void setup_stack_debug_init();
void setup_stack_debug_update();
void setup_draw_stack_debug();
u8 setup_tsf_map_addr_to_block(u32 addr, u16 *block, u32 *block_ofs);
void setup_tsf_map_chunk_to_entry(const TSF_CHUNK *chunk, u8 *entry);
void setup_tsf_map_entry_to_chunk(const u8 *entry, TSF_CHUNK *chunk);
void setup_tsf_map_store_chunk(u16 block, const TSF_CHUNK *chunk);
u8 setup_tsf_map_load_chunk(u16 block, TSF_CHUNK *chunk);
void setup_tsf_map_mark_erased_block(u16 block);
void setup_tsf_map_mark_erased_range(u32 addr, u32 size);
void setup_tsf_map_update_write(u32 addr, const void *src, u32 size);
TSF_RESULT setup_tsf_flash_read_raw(u32 addr, void *dst, u32 size);
u8 setup_tsf_rebuild_block_map();
void setup_flash_detect();
void setup_tsf_set_flash_addr(u32 addr);
void setup_tsf_wait_ready();
TSF_RESULT setup_tsf_hal_read(u32 addr, void *dst, u32 size);
TSF_RESULT setup_tsf_hal_write(u32 addr, const void *src, u32 size);
TSF_RESULT setup_tsf_hal_erase_cmd(u32 addr, u8 cmd);
TSF_RESULT setup_tsf_hal_erase(u32 addr);
TSF_RESULT setup_tsf_hal_erase_range(u32 addr, u32 size);
void setup_tsf_config_init();
void setup_tsf_mount_volume();
void setup_copy_name(char *dst, const char *src, u8 max_len);
void setup_host_dir_clear_buf();
u32 setup_host_dir_get_u32(u8 ofs);
void setup_host_dir_put_u32(u8 ofs, u32 value);
void setup_host_dir_store_entry(u32 base, u8 index, const char *name, u32 size, u8 is_dir, u32 aux, u8 aux_valid);
void setup_host_dir_invalidate_entry(u32 base, u8 index);
void setup_host_dir_mark_end(u32 base, u8 count);
u8 setup_host_dir_load_entry(u32 base, u8 index, char *name, u32 *size, u8 *is_dir, u32 *aux, u8 *aux_valid);
u8 setup_tsf_rebuild_dir_cache();
u8 setup_tsf_get_entry(u8 index, char *name, u32 *size);
u8 setup_tsf_get_entry_head(u8 index, char *name, u32 *size, u32 *head_addr, u8 *head_valid);
u8 setup_name_equal(const char *a, const char *b);
u8 setup_tsf_cached_head_by_name(const char *name, u32 *size, u32 *head_addr, u8 *head_valid);
u8 setup_tsf_name_len(const char *name);
u8 setup_tsf_open_read_at(TSF_VOLUME *vol, TSF_FILE *file, const char *name, u32 head_addr);
TSF_RESULT setup_tsf_open_read_cached(TSF_VOLUME *vol, TSF_FILE *file, const char *name, u32 head_addr, u8 head_valid);
TSF_RESULT setup_tsf_open_read_cached_by_name(TSF_VOLUME *vol, TSF_FILE *file, const char *name);
void setup_sd_update_free();
u8 setup_sd_count_entries();
void setup_sd_mount();
u8 setup_sd_get_entry(u8 index, char *name, u32 *size, u8 *is_dir);
u8 setup_sd_path_len();
void setup_sd_path_parent();
u8 setup_sd_path_append(const char *name);
void setup_sd_reload_panel();
void setup_sd_refresh_panel();
void setup_sd_path_last_name(char *name);
void setup_panel_select_index(SetupPanel *p, u8 index);
u8 setup_sd_select_name(const char *name);
void setup_tsf_refresh_panel_light();
u8 setup_name_extension_type(const char *name);
u8 setup_fpga_set_current_config(const char *name, u8 type);
u8 setup_fpga_config_start();
void setup_fpga_release_runtime_pins();
void setup_fpga_prepare_tsf();
void setup_fpga_halt_after_load();
void setup_fpga_save_run_now_name(const char *name);
void setup_fpga_request_run_now(const char *name);
u8 setup_fpga_load_rbf_now(const char *name, u32 size);
u8 setup_mlz_next_byte();
void setup_mlz_put_byte(u8 byte);
u8 setup_mlz_get_bits(u8 numbits);
void setup_mlz_repeat(s16 disp, u8 len);
u8 setup_fpga_load_mlz_now(const char *name);
u8 setup_fpga_load_now(const char *name, u8 type, u32 size);
void setup_tsf_enter_active();
void setup_fpga_action();
u8 setup_sd_build_path(const char *name);
void setup_mkdir_show_dialog();
u8 setup_scancode_to_char(u8 code);
void setup_mkdir_add_char(u8 ch);
void setup_mkdir_backspace();
void setup_mkdir_create();
void setup_draw_mkdir_text(u8 rel_row);
void setup_draw_mkdir_window_row(u8 row);
void setup_draw_copy_confirm_text(u8 rel_row);
void setup_draw_copy_confirm_window_row(u8 row);
void setup_draw_copy_text(u8 rel_row);
void setup_draw_copy_window_row(u8 row);
void setup_draw_copy_window();
void setup_copy_set_progress(u32 done, u32 total);
void setup_copy_show_window();
void setup_copy_show_error(u8 error);
void setup_copy_hide_window();
u8 setup_copy_can_active_file();
void setup_copy_show_confirm();
u32 setup_tsf_required_space(u32 size, const char *name);
u8 setup_copy_sd_to_tsf();
u8 setup_copy_tsf_stream_segment_to_sd(u32 addr, u32 size, u32 *done, u32 total, FRESULT *fr_out);
u8 setup_copy_tsf_advance_read_chunk();
u8 setup_copy_tsf_to_sd();
void setup_copy_active_file();
void setup_rom_set_progress(u32 done, u32 total);
u8 setup_rom_can_active_file();
void setup_rom_put_hex_addr_at(u8 x, u32 addr, u8 attr);
void setup_rom_exit_id_mode();
void setup_rom_read_chip_id();
void setup_rom_show_dialog();
u8 setup_rom_open_file();
void setup_rom_close_file();
u8 setup_rom_read_file(u8 *buf, u16 size);
void setup_rom_reset_flash();
void setup_rom_unlock();
u8 setup_rom_poll_cancel();
u8 setup_rom_wait_expected(u32 addr, u8 expected, u32 timeout, u8 stable_reads, u8 slow);
u8 setup_rom_wait_erase_done(u32 addr);
u8 setup_rom_wait_toggle(u32 addr, u8 expected, u32 timeout, u8 slow);
u8 setup_rom_wait_program_done(u32 addr, u8 expected);
u8 setup_rom_erase_block(u32 addr);
u8 setup_rom_verify_erased_block(u32 addr);
u8 setup_rom_program_byte(u32 addr, u8 data);
u8 setup_rom_erase_blocks(u32 *done, u32 total);
u8 setup_rom_program_file(u32 *done, u32 total);
u8 setup_rom_read_verify_byte(u32 addr, u8 expected, u8 *actual);
u8 setup_rom_verify_file(u32 *done, u32 total);
void setup_rom_program_active_file();
void setup_draw_rom_status(u8 x);
void setup_draw_rom_text(u8 rel_row);
void setup_draw_rom_window_row(u8 row);
u8 setup_delete_can_active_file();
void setup_delete_show_confirm();
void setup_draw_delete_name(u8 x, u8 max_len, u8 attr);
void setup_draw_delete_text(u8 rel_row);
void setup_draw_delete_window_row(u8 row);
void setup_delete_set_progress(u32 done, u32 total);
void setup_delete_progress_cb(u32 done, u32 total);
void setup_delete_active_file();
void setup_sd_go_parent();
void setup_sd_open_active();
u8 setup_panel_count(u8 panel);
u8 setup_get_entry_info(u8 panel, u8 index, char *name, u32 *size);
u8 setup_active_entry(u8 panel);
u8 setup_u32_to_dec(char *dst, u32 value);
void setup_put_dec_right(u8 right_x, u32 value, u8 attr);
void setup_put_dec_at(u8 x, u32 value, u8 attr);
void setup_append_char(char *dst, u8 *pos, u8 max, char ch);
void setup_append_text_buf_p(char *dst, u8 *pos, u8 max, const char *text);
void setup_append_u32(char *dst, u8 *pos, u8 max, u32 value);
void setup_size_to_text(char *dst, u32 value);
void setup_put_hex_byte(u8 x, u8 value, u8 attr);
void setup_draw_panel_file_info(u8 panel, u8 x);
void setup_draw_key_hint();
void setup_draw_help_text(u8 rel_row);
void setup_draw_help_window_row(u8 row);
void setup_eeprom_draw_name(u8 x, u8 max_len);
u8 setup_put_dec_move(u8 x, u32 value, u8 attr);
u8 setup_eeprom_put_tlv_tag(u8 x, u8 tag);
void setup_eeprom_draw_tlv_item(u8 x, u8 tag, u8 len);
void setup_eeprom_draw_tlv_records(u8 rel_row);
void setup_draw_eeprom_text(u8 rel_row);
void setup_draw_eeprom_window_row(u8 row);
void setup_eeprom_show_dialog();
void setup_draw_format_choice(u8 option, const char *text);
void setup_draw_format_text(u8 rel_row);
void setup_draw_format_window_row(u8 row);
void setup_draw_chkdsk_choice(u8 option, const char *text);
void setup_draw_chkdsk_stats_line(u8 rel_row);
void setup_draw_chkdsk_text(u8 rel_row);
void setup_draw_chkdsk_window_row(u8 row);
void setup_draw_chkdsk_window();
void setup_start_chkdsk();
void setup_draw_fpga_text(u8 rel_row);
void setup_draw_fpga_window_row(u8 row);
void setup_draw_dialogs_row(u8 row);
void setup_draw_dialog_area(u8 x, u8 y, u8 w, u8 h);
void setup_draw_help_window();
void setup_draw_eeprom_window();
void setup_draw_fpga_window();
void setup_draw_mkdir_window();
void setup_draw_copy_confirm_window();
void setup_draw_rom_window();
void setup_draw_delete_window();
void setup_draw_format_window();
u8 setup_format_poll_cancel();
void setup_format_set_progress(u16 done, u16 total);
void setup_format_begin_stage(u8 stage);
TSF_RESULT setup_format_tsf_poll();
TSF_RESULT setup_tsf_blankcheck_stream(u32 addr, u32 size, u8 (*poll_func)());
TSF_RESULT setup_tsf_blankcheck_stream_format(u32 addr, u32 size);
void setup_format_badmap_clear();
u8 setup_format_badmap_can_track();
void setup_format_badmap_set(u16 block);
u8 setup_format_badmap_get(u16 block);
void setup_format_badmap_clear_block(u16 block);
u16 setup_format_badmap_count();
u8 setup_tsf_wait_ready_format();
TSF_RESULT setup_tsf_hal_erase_cmd_format(u32 addr, u8 cmd);
TSF_RESULT setup_tsf_hal_erase_range_format(u32 addr, u32 size);
u8 setup_tsf_probe_erase_cmd(u8 cmd, u32 erase_size);
TSF_RESULT setup_tsf_format_block_erase(u8 cmd, u32 erase_size);
TSF_RESULT setup_tsf_format_selected();
void setup_start_format();
u8 setup_chkdsk_poll_cancel();
TSF_RESULT setup_chkdsk_tsf_poll();
TSF_RESULT setup_tsf_blankcheck_stream_chkdsk(u32 addr, u32 size);
u8 setup_tsf_wait_ready_chkdsk();
TSF_RESULT setup_tsf_hal_erase_cmd_chkdsk(u32 addr, u8 cmd);
u8 setup_tsf_read_chunk(u16 block, TSF_CHUNK *chunk);
u8 setup_tsf_chunk_valid(u16 block, TSF_CHUNK *chunk);
u8 setup_tsf_chain_reaches(u16 head_block, u16 target_block);
u8 setup_tsf_body_referenced(u16 body_block);
void setup_chkdsk_reset_stats();
TSF_RESULT setup_tsf_recover_block(u16 block);
void setup_tsf_update_recover_stats(TSF_CHUNK *chunk);
TSF_RESULT setup_tsf_recover_file_chain(u16 head_block);
u8 setup_tsf_check_head_file(u16 head_block, u8 count_stats, u8 mark_refs);
void setup_chkdsk_set_progress(u16 done, u16 total);
void setup_chkdsk_begin_stage(u8 stage);
TSF_RESULT setup_tsf_chkdsk_run();
void setup_draw_tsf_no_flash_box(u8 row);
void setup_put_entry(u8 panel, u8 x, u8 entry_row);
void setup_draw_panel_entries(u8 row);
void setup_clear_range(u8 x, u8 w, u8 attr);
void setup_fill_attr_range(u8 x, u8 w, u8 attr);
void setup_draw_panel_info_only(u8 panel);
void setup_draw_panel_cursor_move(u8 panel, u8 old_cursor, u8 new_cursor);
void setup_draw_panel_cursor_attr(u8 panel, u8 attr);
void setup_draw_panel_active_switch(u8 old_panel, u8 new_panel);
void setup_draw_panels_area(u8 x, u8 y, u8 w, u8 h);
void setup_draw_panels();
void setup_panel_fix_cursor(SetupPanel *p);
void setup_panel_move_up(SetupPanel *p);
void setup_panel_move_down(SetupPanel *p);
void setup_panel_page_up(SetupPanel *p);
void setup_panel_page_down(SetupPanel *p);
void setup_panel_home(SetupPanel *p);
void setup_panel_end(SetupPanel *p);
void setup_exit_to_runtime();
void setup_handle_key(u8 ext, u8 code);
void setup_process_scancode(u8 code);

void sfi_enable();
void sfi_disable();
void sfi_cs_on();
void sfi_cs_off();
void sfi_send(u8 d);
u8 sfi_recv();
#endif

#endif
