#define     WIN_COL_BLACK           0
#define     WIN_COL_BLUE            1
#define     WIN_COL_RED		        2
#define     WIN_COL_MAGENTA         3
#define     WIN_COL_GREEN	        4
#define     WIN_COL_CYAN	        5
#define     WIN_COL_YELLOW	        6
#define     WIN_COL_WHITE	        7
#define     WIN_COL_BRIGHT_BLUE	    9
#define     WIN_COL_BRIGHT_RED      10
#define     WIN_COL_BRIGHT_MAGENTA	11
#define     WIN_COL_BRIGHT_GREEN    12
#define     WIN_COL_BRIGHT_CYAN     13
#define     WIN_COL_BRIGHT_YELLOW   14
#define     WIN_COL_BRIGHT_WHITE    15
